### ISSUE TITLE
A few parts appear to be in the wrong orientation for pcba

### ISSUE THREAD

**Issue by mrlinuxfish** [jfedor2/rp2040-pmw3360#1]
When I try to order from jlcpcb, a few of the parts look like they're loading in the assembly the wrong way around

![image](https://user-images.githubusercontent.com/444722/139598921-ec78177e-a1f9-4e4d-9b7c-dc1b7ef2b63b.png)

**Comment by jfedor2** [comment]
Yeah, that's normal with files exported from KiCad. I guess there's more than one convention when it comes to the part orientation and JLCPCB uses a different one. Might be worth fixing, but it's not a problem when ordering PCBs from them (I've done it with these exact files). What happens is a human looks at the files and fixes the orientations before the PCBs are fabricated.

**Comment by mrlinuxfish** [comment]
Awesome, as long as they get produced correctly there shouldn't be any problem
