### ISSUE TITLE
cheaper assembly  suggestion

### ISSUE THREAD

**Issue by itsnoteasy** [jfedor2/rp2040-pmw3360#3]
i'm about to order this but was horrified at the expense of the extended components which require adding a reel for a fee of around 6 euro per reel last time i checked. the csv and bom file generation was beyond me so i'm gonna put up with it. here's a few suggestions anyway.

replace r1 39 ohm resistor with a pair of resistors 49.9ohm and 180ohm in parallel for 39.3ohm these can be sourced in 0603 size.
likewise replace r3 and r4 with a larger size.
remove sw1 and sw2, these can be hand soldered.
I have edited the bom and csv of the last two and shaved 5 euro off my order. i cannot easily change the 39 ohm resistor.
i won't complain about the voltage regulators because they are an ephemeral purchase, but come on, 5 euro for a resistor is far too expensive.

**Comment by itsnoteasy** [comment]
If you like then you can break out GPIO0 beside GPIO1(motion). this would allow the pcb to be reused as a hid-remapper, although the existing pcb should be able to make a dual rp2040 version.

**Comment by jfedor2** [comment]
You should be able to use the board for HID Remapper as is, the pins used for the USB interface are configurable. You'd have to recompile the firmware.

**Comment by itsnoteasy** [comment]
I figured as much but i made this issue as a way to track improvements if anyone was to make another version down the line.
