### ISSUE TITLE
CPL missing designators

### ISSUE THREAD

**Issue by ajk1982** [jfedor2/rp2040-pmw3360#5]
The below parts won't be assembled due to data missing.
J1,J2,H1,H2,H3,H4,U2 designators don't exist in the CPL file.
<img width="498" alt="Screenshot 2024-05-29 at 14 31 57" src="https://github.com/jfedor2/rp2040-pmw3360/assets/1137677/9bf721bf-5b35-4b4e-a9e8-6358478e00fc">

**Comment by ajk1982** [comment]
My mistake!

**Comment by elliotf** [comment]
What was the mistake that you made, @ajk1982 ? I'm also getting the same error when attempting to get the board fabricated.

**Comment by ajk1982** [comment]
@elliotf I actually can't remember. I will ask the electronics guy at work tomorrow to take a look because when I try it now I get the same problem.

**Comment by jfedor2** [comment]
These designators are the headers, mounting holes and the sensor chip. They shouldn't be in the BOM file in the first place (my mistake). You can safely ignore this error.

**Comment by elliotf** [comment]
Thank you, @jfedor2 and @ajk1982 -- I can continue past that error. Thank you again!
