### ISSUE TITLE
Flashing Instructions

### ISSUE THREAD

**Issue by dahmwern** [jfedor2/rp2040-pmw3360#6]
Can you provide some flashing instructions for the PCB and sensor? I'm seeing multiple sets of .c and .h files. It would be helpful if you could shed some light into what needs to be flashed or configured here. Any help would be greatly appreciated! 

My PCB is being assembled now and trackball housing design is being finalized before printing.

**Comment by jfedor2** [comment]
Press and hold the BOOT button and while holding it, press and release the RESET button.

A drive named "RPI-RP2" will appear on your computer. Copy the UF2 file to it.

**Comment by dahmwern** [comment]
I spent too much time looking at the code files, and missed the .uf2! Thanks!
