### ISSUE TITLE
how to adjust lift off distance?

### ISSUE THREAD

**Issue by dahmwern** [jfedor2/rp2040-pmw3360#7]
Can you provide guidance on the correct way to adjust lift off distance in the code?

**Comment by jfedor2** [comment]
From what I can see in the datasheet you can choose between 2 and 3 mm by writing those values to register Lift_Config (0x63).

There's also some calibration procedure, but I never tried it.

**Comment by dahmwern** [comment]
Closing this issue, thank you!
